export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_ADD_SUCCESS = 'CART_ADD_SUCCESS';
export const CART_ADD_FAIL = 'CART_ADD_FAIL';

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS';
export const CART_LIST_FAIL = 'CART_LIST_FAIL';

export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_REMOVE_FAIL = 'CART_REMOVE_FAIL';
export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';
